# Generated by Django 2.1.2 on 2018-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0003_auto_20181117_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
