# Generated by Django 2.1.2 on 2018-12-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0004_userprofile_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileImage',
            new_name='image',
        ),
    ]
