# Generated by Django 2.1.2 on 2018-12-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0005_auto_20181206_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profileImage',
        ),
    ]
