# Generated by Django 2.1.2 on 2018-12-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0007_auto_20181207_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/'),
        ),
    ]
