# Generated by Django 2.1.2 on 2018-12-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0008_auto_20181207_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/%Y/%m/%d'),
        ),
    ]
