# Generated by Django 2.1.2 on 2018-12-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0012_auto_20181211_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(upload_to='profileimage'),
        ),
    ]
