# Generated by Django 2.1.2 on 2018-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0013_auto_20181211_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage'),
        ),
    ]
