# Generated by Django 2.1.2 on 2018-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0015_auto_20181211_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
