# Generated by Django 2.1.2 on 2018-12-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingapp', '0016_auto_20181212_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.FloatField(null=True),
        ),
    ]
